### ISSUE TITLE
question about mender install/commit and this repo

### ISSUE THREAD

**Issue by arrow53** [OE4T/tegra-demo-distro#16]
@dwalkes This isn't really so much an issue as a question about the wiki 

https://github.com/OE4T/tegra-demo-distro/wiki/Mender-Integration-Tests

Is it true that upon a success `mender -install` that nvbootctrl will always just switch to the opposite active boot slot from the one it is currently in? So, basically the last good update becomes the new "golden/fallback" image?

From the wiki I see that if the install is interrupted (loss of power) mender will stay in the current slot.

Is it necessary to ever issue `mender -commit`?

**Comment by dwalkes** [comment]
@arrow53 

> This isn't really so much an issue as a question about the wiki https://github.com/OE4T/tegra-demo-distro/wiki/Mender-Integration-Tests

I was proposing those tests as a way to resolve https://github.com/BoulderAI/meta-mender-community/pull/1 - however these aren't ready to go upstream yet.  I've edited to make it clear those instructions are work in progress.

> Is it true that upon a success mender -install that nvbootctrl will always just switch to the opposite active boot slot from the one it is currently in? So, basically the last good update becomes the new "golden/fallback" image?

Yes.

> Is it necessary to ever issue mender -commit?

Yes, assuming you don't have the changes in https://github.com/BoulderAI/meta-mender-community/pull/1 and you are using uboot.  I was proposing adding something in https://github.com/BoulderAI/meta-mender-community/pull/1 for auto-commit, which is especially important for u-boot because there's a possibility to mismatch your boot and root filesystem slots if rollback happens, and rollback will happen automatically if you reboot without `-commit` on `u-boot` platforms.  On `cboot` platforms rollback from mender will happen, however it won't actually do anything since it's not used.  See https://github.com/OE4T/meta-mender-community/pull/8 and discussion at https://github.com/OE4T/meta-mender-community/pull/8#issuecomment-725053394 for more details.

**Comment by arrow53** [comment]
@dwalkes sorry. I read this and it was very helpful. Forgot to comment/close.
