### ISSUE TITLE
Fails to boot on successful flash for machine jetson-nano-emmc on changing rootfs size

### ISSUE THREAD

**Issue by jajoosiddhant** [OE4T/tegra-demo-distro#37]
MACHINE `jetson-nano-emmc` fails to boot up after making the changes to the default `ROOTFSPART_SIZE` from 5233442816 to 4700000000 (or any other value).
`ROOTFSPART_SIZE = "4700000000"` was added in the `build/conf/local.conf` file to modify the rootfs size. 
The failure can be seen on both the dunfell and master branches.

Output of the Test scenario on assigning `ROOTFSPART_SIZE` value `4700000000`

MACHINE `jetson-nano-emmc` flashes successfully as per:
```
[ 128.7239 ] [................................................] 100%
[ 128.7398 ] Writing partition APP_b with core-image-dev.ext4.img
[ 128.7769 ] [................................................] 100%
[ 250.8511 ] Writing partition UDA with core-image-dev-bulletcam.dataimg.img
[ 252.2688 ] [................................................] 100%
[ 252.8476 ]
[ 252.8504 ] tegradevflash --write BCT bulletcam.bct
[ 252.8526 ] Cboot version 00.01.0000
[ 252.8546 ] Writing partition BCT with bulletcam.bct
[ 252.8553 ] [................................................] 100%
[ 253.2510 ]
[ 253.2511 ] Flashing completed

[ 253.2513 ] Coldbooting the device
[ 253.2537 ] tegradevflash --reboot coldboot
[ 253.2561 ] Cboot version 00.01.0000
[ 253.2584 ]
```

**but** fails to boot up as per the messages on serial port:

```
[0000.375] GSC3 Carveout Base=0x000000017f300000 Size=0x00d00000
[0000.391] RamDump Carveout Base=0x00000000ff280000 Size=0x00080000
[0000.397] Platform-DebugCarveout: 0
[0000.401] Nck Carveout Base=0x00000000ff080000 Size=0x00200000
[0000.406] Non secure mode, and RB not enabled.
[0000.423] Csd NumOfBlocks=0
[0000.614] *** Booting BFS1.
[0000.617] Read PT from (0:3)
[0000.623] Using BFS PT to query partitions
[0000.628] PT: Partition LNX NOT found !
[0001.223] *** Failing over to KFS2.
```

**Comment by madisongh** [comment]
I don't think it's documented very well, but the NVIDIA bootloaders have some restrictions on placement of boot partitions.  In particular, the starting LBA has to have a particular alignment.  The details vary among the different chip models, and I don't remember them off the top of my head.  The tools don't necessarily enforce the requirements, either.

So the problem is that you can't set ROOTFSPART_SIZE to any arbitrary value, since that will throw off the alignment of the other partitions, including the ones that the bootloaders need to find (unless you hand-craft the flash layout XML file).  Try sticking to an even multiple of 1MiB, as I think that will be safe in all cases.  For example, replacing your 4700000000 with 4699717632 (4482 MiB) worked fine in my tests.

**Comment by jajoosiddhant** [comment]
@madisongh Thank you for your help on this. I was able to make it work as you mentioned by sticking to even multiples of 1MiB. 
I have updated the documentation [here](https://github.com/OE4T/tegra-demo-distro/wiki/Customization-of-Storage-Size-on-Mender-Builds) to inform about the same. Please let me know if this needs to be updated somewhere else as well or if you want to do it differently.
